### ISSUE TITLE
Adding separate line in SCSS file?

### ISSUE THREAD

**Issue by andyduong1920** [rafayet-monon/react-blog#5]
![image](https://user-images.githubusercontent.com/11751745/87382621-95c07700-c5c1-11ea-806d-b4f95fe2e2df.png)

What do you think if we could add some separate line in the SCSS file, like this

![image](https://user-images.githubusercontent.com/11751745/87382651-aa9d0a80-c5c1-11ea-94d4-87406bdf3978.png)

**Comment by rafayet-monon** [comment]
That should make CSS much more readable. Noted! @anduonghien

**Comment by andyduong1920** [comment]
@rafayet-monon I suggest to use some `lint` library with the `format` tool automatically when you save the css file so no need to do that manually.

If you are using VSCode, I think there is 1 nice extension is https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

I think that is available on the other editor too, check it out at https://prettier.io/

**Comment by rafayet-monon** [comment]
Yeah, I am using webstrom from Jetbrains and configured it that way and then refactored all the files together.

**Comment by andyduong1920** [comment]
Nice @rafayet-monon
